"""Declarative base and shared column conventions.

Every model inherits from `Base`. Two reusable building blocks live here so the
models stay declarative and free of boilerplate:

  * `uuid_pk`  - an Annotated type for a UUID primary key generated by Postgres.
  * `TimestampMixin` - created_at / updated_at handled by the database, not Python,
    so timestamps are consistent regardless of which app instance wrote the row.
"""

import uuid
from datetime import datetime
from typing import Annotated

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


# Postgres 13+ ships gen_random_uuid() in core, so no pgcrypto extension needed.
# UUID keys are non-sequential, which keeps record counts and IDs un-guessable
# in a public API.
uuid_pk = Annotated[
    uuid.UUID,
    mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
]


class TimestampMixin:
    """Adds DB-managed created_at / updated_at to any model."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
